public  class AccountriggerClass {
   /* public static void createRelatedContact(list<account> accListtrigger){
        try{
        list<Contact> conList = new list<Contact>();
        for(Account acc: accListtrigger){
            Contact con = new Contact();
              con.status__c= false;
              con.AccountId = acc.Id;
              conList.add(con);       
        }   
        if(!conList.isEmpty()){
            insert conList;         
        }          
              }
            catch (Exception e) {
             system.debug('Please see the Error'+e.getMessage());
             for(account acc1: accListtrigger){
               acc1.addError('Error please contact to ..Admin');
            }
         }
        }*/
      }


 
